import styles from "@/styles/Home.module.css";
import Head from "next/head";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by Create Next App" />
        <meta name="keywords" content="nextjs, hunting coder blog, hunting coder" />
        <link rel="shortcut icon" href="favicon.ico"/>
      </Head>
      <div className={styles.blogContainer}>
        <div className={styles.imgContainer}>
          <img
            className={styles.myImg}
            src="/home-img.avif"
            width={200}
            height={120}
            alt="hunting coder"
          />
        </div>
        <h1 className={styles.heading}>
          <span>&lt;HuntingCoder /&gt;</span>
        </h1>
        <div className={styles.popularBlogs}>
          <h2>Latest Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to Learn JavaScript in 2022?</h3>
            <p>JavaScript is the language to design logic for the web.</p>
            <button className={styles.btn}>Read More</button>
          </div>

          <div className={styles.blogItem}>
            <h3>How to Learn NextJs in 2022?</h3>
            <p>NextJs is the language to design logic for the web.</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogItem}>
            <h3>How to Learn Flask in 2022?</h3>
            <p>Flask is the language to design logic for the web.</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </div>
    </div>
  );
}
